services:
  datamanager:
    platform: linux/amd64
    build:
      context: ./DataManager
      dockerfile: dataManager.Dockerfile
    container_name: dataManager
    ports:
      - "5266:5266"
      - "7066:7066"
    volumes:
      - ./DataManager/src:/src
    environment:
      - ASPNETCORE_URLS=http://+:5266
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=hmDB;Username=postgres
    depends_on:
      - mosquitto

  gateway:
    build:
      context: ./Gateway
      dockerfile: gateway.Dockerfile
    container_name: gateway
    ports:
      - "3000:3000"
    volumes:
      - ./Gateway/src:/app/src
    depends_on:
      - datamanager

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    #restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      #- ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  eventmanager:
    build:
      context: ./EventManager
      dockerfile: eventmanager.Dockerfile
    container_name: eventmanager
    ports:
      - "3001:3001"
    volumes:
      - ./EventManager/src:/app/src
    depends_on:
      - mosquitto
  postgres:
    image: postgres:latest
    container_name: postgreDB
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # - POSTGRES_USER=meda
      # - POSTGRES_PASSWORD=meda
      - POSTGRES_DB=hmDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  analytics:
    build:
      context: ./Analytics
      dockerfile: ./analytics.Dockerfile
    volumes:
      - ./Analytics:/app
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
      - mlaas

  mlaas:
    build:
      context: ./MLaaS
      dockerfile: ./mlaas.Dockerfile
    volumes:
      - ./MLaaS:/app
    ports:
      - "8001:8001"

volumes:
  postgres_data:
