// <auto-generated />
using System;
using DataManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataManager.Migrations
{
    [DbContext(typeof(HealthRecordDbContext))]
    [Migration("20251008192226_malaslova")]
    partial class malaslova
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataManager.Models.HealthRecordModel", b =>
                {
                    b.Property<int>("recordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("recordId"));

                    b.Property<string>("activityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Activity_Status");

                    b.Property<string>("athleteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("athlete_id");

                    b.Property<int>("bloodOxygen")
                        .HasColumnType("integer")
                        .HasColumnName("blood_oxygen");

                    b.Property<string>("bloodPressure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plood_pressure");

                    b.Property<float>("bodyTemperature")
                        .HasColumnType("real")
                        .HasColumnName("body_temperature");

                    b.Property<int>("heartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("secureTransmissionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("secure_transmission_status");

                    b.Property<int>("stepCount")
                        .HasColumnType("integer")
                        .HasColumnName("step_count");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("recordId");

                    b.ToTable("health_data");
                });
#pragma warning restore 612, 618
        }
    }
}
