// <auto-generated />
using System;
using DataManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataManager.Migrations
{
    [DbContext(typeof(HealthRecordDbContext))]
    partial class HealthRecordDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataManager.Models.HealthRecordModel", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("record_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RecordId"));

                    b.Property<string>("ActivityStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Activity_Status");

                    b.Property<string>("AthleteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("athlete_id");

                    b.Property<int>("BloodOxygen")
                        .HasColumnType("integer")
                        .HasColumnName("blood_oxygen");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plood_pressure");

                    b.Property<float>("BodyTemperature")
                        .HasColumnType("real")
                        .HasColumnName("body_temperature");

                    b.Property<int>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("SecureTransmissionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("secure_transmission_status");

                    b.Property<int>("StepCount")
                        .HasColumnType("integer")
                        .HasColumnName("step_count");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("RecordId");

                    b.ToTable("health_data");
                });
#pragma warning restore 612, 618
        }
    }
}
